djangodjitney/djangodjitney/urls.py
from django.contrib import admin
from django.urls import path

from routes import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.HomeView.as_view(), name='home'),
    path('lines/', views.LinesView.as_view(), name='lines'),
    path('lines/new', views.CreateLineView.as_view(), name="create_line"),
    path('lines/<pk>/update/', views.UpdateLineView.as_view(), name="update_line"),
    path('lines/<pk>/delete', views.DeleteLineView.as_view(), name="delete_line"),
    path('stations/', views.StationsView.as_view(), name="stations"),
    path('stations/new/', views.CreateStationView.as_view(), name="create_station"),
    path('stations/<pk>/update', views.UpdateStationView.as_view(), name="update_station"),
    path('stations/<pk>/delete', views.DeleteStationView.as_view(), name="delete_station"),
    path('stops/', views.StopView.as_view(), name="stops"),
    path('stops/new', views.CreateStopView.as_view(), name="create_stop"),
    path('stops/<pk>/update', views.UpdateStopView.as_view(), name="update_stop"),
    path('stop/<pk>/delete', views.DeleteStopView.as_view(), name="delete_stop")
]

djangodjitney/routes/models.py
from django.db import models

# Create your models here.
class Line(models.Model):
    name = models.CharField(unique=True, max_length=200)
    
    def get_absolute_url(self):
        return "/lines"
    
    def __str__(self):
        return f"{self.name}"
    
class Station(models.Model):
    name = models.CharField(unique=True, max_length=200)
    accessible = models.BooleanField(default=False)
    
    def get_absolute_url(self):
        return "/stations"
    
    def __str__(self):
        return f"{self.name}{'(♿)' if self.accessible else ''}"

class Stop(models.Model):
    # The snippet of code below ensures that no line can have two stops with the same stop number
    class Meta:
        unique_together = (('line', 'stop_number'))

    def get_absolute_url(self):
        return "/stops"

    line = models.ForeignKey(Line, on_delete=models.CASCADE)
    station = models.ForeignKey(Station, on_delete=models.CASCADE)
    stop_number = models.PositiveIntegerField()

    def __str__(self):
        return f"{self.line.name} -- {self.station.name} [{self.stop_number}]"    

djangodjitney/routes/forms.py
from django import forms
from .models import Stop, Station, Line

class StopForm(forms.ModelForm):
    class Meta:
        model = Stop
        fields = "__all__"
        
        
class LineForm(forms.ModelForm):
    class Meta:
        model = Line
        fields = "__all__"
        

class StationForm(forms.ModelForm):
    class Meta:
        model = Station
        fields = "__all__"

djangodjitney/routes/admin.py
from django.contrib import admin

# Register your models here.

djangodjitney/routes/apps.py
from django.apps import AppConfig


class RoutesConfig(AppConfig):
    default_auto_field = 'django.db.models.BigAutoField'
    name = 'routes'

djangodjitney/routes/tests.py
from django.test import TestCase

# Create your tests here.

djangodjitney/routes/views.py
from typing import Any
from django.shortcuts import render

from .models import Line, Stop, Station
from .forms import StopForm, LineForm, StationForm

# Import views templates
from django.views.generic import TemplateView, ListView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy

# Create your views here.
# home views
class HomeView(TemplateView):
    template_name = "routes/home.html"
    
    def get_context_data(self):
        context = super().get_context_data()
        context["lines"] = Line.objects.all()
        context["stations"] = Station.objects.all()
        context["stops"] = Stop.objects.all()
        
        return context

"""
Views for Lines: list view, CRUD views.
"""
# List View of Lines
class LinesView(ListView):
    model = Line
    template_name = "routes/lines.html"
    
# Create Lines view
class CreateLineView(CreateView):
    model = Line
    template_name = "routes/add_line.html"
    form_class = LineForm
    
# Update Lines View
class UpdateLineView(UpdateView):
    model = Line
    template_name = "routes/update_line.html"
    form_class = LineForm
    
# Delete Lines View
class DeleteLineView(DeleteView):
    model = Line
    template_name = "routes/delete_line.html"
    # Need to define a success_url after delete is success.
    success_url = reverse_lazy("lines")
    

"""
Views for Station
"""
class StationsView(ListView):
    model = Station
    template_name = "routes/stations.html"
    

class CreateStationView(CreateView):
    model = Station
    template_name = "routes/add_station.html"
    form_class = StationForm
    
class UpdateStationView(UpdateView):
    model = Station
    template_name = "routes/update_station.html"
    form_class = StationForm
    
class DeleteStationView(DeleteView):
    model = Station
    template_name = "routes/delete_station.html"
    success_url = reverse_lazy("stations")
    
    
"""
Views for Stops
"""
class StopView(ListView):
    model = Stop
    template_name = "routes/stops.html"
    
class CreateStopView(CreateView):
    model = Stop
    template_name = "routes/add_stop.html"
    form_class = StopForm
    
class UpdateStopView(UpdateView):
    model = Stop
    template_name = "routes/update_stop.html"
    form_class = StopForm
    
class DeleteStopView(DeleteView):
    model = Stop
    template_name = "routes/delete_stop.html"
    success_url = reverse_lazy("stops")

djangodjitney/routes/templates/base.html
<!DOCTYPE html>
<head>
    <meta charset="UTF-8">

    <link 
      rel="shortcut icon"
      type="image/x-icon"
      href="https://www.codecademy.com/favicon.ico"
    />

    <!--{# Load all statics #}-->
    {% load static %}

    {% block head %}
    {% endblock %}
    <!-- {# Load bootstrap #} -->
    {% load bootstrap5 %}
    {% bootstrap_css %}
    {% bootstrap_javascript %}

    <!-- Load custom stylesheet -->
    <link rel="stylesheet" type="text/css" href="{% static 'routes/style.css' %}">

    <!-- {# Load fontawesome svg #} -->
    <script src="{% static 'fontawesomefree/js/fontawesome.js' %}"></script>
    <script src="{% static 'fontawesomefree/js/solid.js' %}"></script>
    <script src="{% static 'fontawesomefree/js/brands.js' %}"></script>

    <!-- {# Load google font Roboto #}-->
    <link rel="preconnect" href="https://fonts.gstatic.com" />
    <link
      href="https://fonts.googleapis.com/css2?family=Oxygen:wght@300;400;700&display=swap"
      rel="stylesheet"
    />

    <title>
        {% block title %}Django Djitter{% endblock %}
    </title>
</head>

<body>
    <!-- Nav bar -->
    <div class="container">
        <header>
            <nav class="navbar navbar-expand-sm navbar-light bg-light">
                <!--{# Home button #}-->
                <a class="navbar-brand" href="{% url 'home' %}" id="home" name="home">
                    Home
                </a>

                <!--{# Hamburger button #}-->
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

            <!--{# Nav items #}-->
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url "lines" %}">Lines</a>
                    </li>
                    <li class="nav-item ml-1">
                        <a class="nav-link" href="{% url "stations" %}">Stations</a>
                    </li>
                    <li class="nav-item ml-1">
                        <a class="nav-link" href="{% url "stops" %}">Stops</a>
                    </li>
                </ul>
            </div>

        </nav>
        </header>

        <main>
            {% block content %}{% endblock %}
        </main>
    </div>
</body>

djangodjitney/routes/templates/routes/add_line.html
{% extends 'base.html' %} {% load static %} {% block content %}
<h2>Add a New Djitney Line</h2>
<form method="post">
  {% csrf_token %}
  <div>
    {{ form.as_p }}
    <input type="submit" value="Submit" />
  </div>
</form>
{% endblock %}

djangodjitney/routes/templates/routes/add_station.html
{% extends 'base.html' %} {% load static %} {% block content %}
<h2>Add a New Djitney Station</h2>
<form method="post">
  {% csrf_token %}
  <div>
    {{ form.as_p }}
    <input type="submit" value="Submit" />
  </div>
</form>
{% endblock %}

djangodjitney/routes/templates/routes/add_stop.html
{% extends 'base.html' %} {% load static %} {% block content %}
<h2>Add a New Djitney Stop</h2>
<form method="post">
  {% csrf_token %}
  <div>
    {{ form.as_p }}
    <input type="submit" value="Submit" />
  </div>
</form>
{% endblock %}

djangodjitney/routes/templates/routes/delete_line.html
{% extends 'base.html' %} {% load static %} {% block content %}
<h2>Delete Line</h2>
<form method="post">
  {% csrf_token %}
  <p>Are you sure you want to delete "{{ object }}"?</p>
  <input type="submit" value="Confirm" />
</form>
{% endblock %}

djangodjitney/routes/templates/routes/delete_station.html
{% extends 'base.html' %} {% load static %} {% block content %}
<h2>Delete Station</h2>
<form method="post">
  {% csrf_token %}
  <p>Are you sure you want to delete "{{ object }}"?</p>
  <input type="submit" value="Confirm" />
</form>
{% endblock %}

djangodjitney/routes/templates/routes/delete_stop.html
{% extends 'base.html' %} {% load static %} {% block content %}
<h2>Delete Stop</h2>
<form method="post">
  {% csrf_token %}
  <p>Are you sure you want to delete "{{ object }}"?</p>
  <input type="submit" value="Confirm" />
</form>
{% endblock %}

djangodjitney/routes/templates/routes/home.html
{% extends "base.html" %}
{% load static %}
{% block title %}
Django Djitter - Home
{% endblock %}

{% block content %}
<div class="container">
    <div>
        <h2>Lines</h2>
        {% if lines|length == 0 %}
        <p>No lines to display</p>
        {% else %}
        <table class="line-table">
            <thead>
                <tr>
                    <th>Name</th>
                    <th>Stops</th>
                </tr>
            </thead>
            <tbody>
            {% for line in lines %}
            <tr>
                <td>{{ line.name }}</td>
                <td>
                    <ul>
                        {% for stop in line.stop_set.all %}
                        <li>{{ stop.stop_number }}</li>
                        <div>
                        {{ stop.station.name }}{% if stop.station.accessible %} ♿ {% endif %}
                        </div>
                        {% endfor %}
                    </ul>
                </td>
            </tr>
            {% endfor %}
            </tbody>
        </table>
        {% endif %}
        
    </div>
</div>
{% endblock %}

djangodjitney/routes/templates/routes/lines.html
{% extends 'base.html' %}
{% load static %} 
{% block title %}Django Djitney{% endblock %}
{% block content %}
  <div>
    <h2>Lines</h2>
    <table class="line-table">
      <thead>
        <tr>
          <th>Name</th>
          <th>Stops</th>
          <th>Actions</th>
        </tr>
      </thead>
      <tbody>
      {% for line in object_list %}
        <tr>
          <td>
            <a href="{% url "update_line" line.id %}">{{ line.name }}</a>
          </td>
          <td>
            <ul>
                {% for stop in line.stop_set.all %}
                  <li>{{ stop.stop_number }}</li>
                  <div >{{ stop.station.name }}{% if stop.station.accessible %}  ♿  {% endif %} </div>
                {% endfor %}
            </ul>
          </td>
          <td><a href="{% url "delete_line" line.id %}" style="text-decoration: none; color: inherit;">❌</a></td>
        </tr>
      {% endfor %}
      </tbody>
    </table>
    <a href="{% url "create_line" %}" style="display: inherit; text-align: center; border-radius: 15px; text-decoration: none; color: inherit; padding: 4px; background-color: lightgreen;">➕</a>
  </div>
{% endblock %}

djangodjitney/routes/templates/routes/stations.html
{% extends 'base.html' %}
{% load static %} 
{% block title %}Django Djitney{% endblock %}
{% block content %}
<div>
  <h2>Stations</h2>
  <table class="line-table">
    <thead>
      <tr>
        <th>Name</th>
        <th>On Lines</th>
        <th>Actions</th>
      </tr>
    </thead>
    <tbody>
    {% for station in object_list %}
        <tr>
          <td>
            <a href="{% url "update_station" station.id %}">{{ station.name }}</a>
            {% if station.accessible %}<span>  ♿️ </span>{% endif %}
          </td>
          <td>
            {% for stop in station.stop_set.all %}{{stop.line.name}}, {% endfor %}
          </td>
          <td><a href="{% url "delete_station" station.id %}" style="text-decoration: none; color: inherit;">❌</a></td>
        </tr>
    {% endfor %}
    </tbody>
  </table>
  <a href="{% url "create_station" %}" style="display: inherit; text-align: center; border-radius: 15px; text-decoration: none; color: inherit; padding: 4px; background-color: lightgreen;">➕</a>
</div>
{% endblock %}

djangodjitney/routes/templates/routes/stops.html
{% extends 'base.html' %}
{% load static %} 
{% block title %}Django Djitney{% endblock %}
{% block content %}
  <div>
    <h2>Stops</h2>
    <table class="line-table">
      <thead>
        <tr>
          <th>Line</th>
          <th>Stop Number</th>
          <th>Station</th>
          <th>Actions</th>
        </tr>
      </thead>
      <tbody>
      {% for stop in object_list %}
        <tr>
          <td>{{ stop.line.name }}</td>
          <td><a href="{% url "update_stop" stop.id %}">{{ stop.stop_number }}</a></td>
          <td>{{ stop.station.name }}</td>
          <td><a href="{% url "delete_stop" stop.id %}" style="text-decoration: none; color: inherit;">❌</a></td>
        </tr>
      {% endfor %}
      </tbody>
    </table>
    <a href="{% url "create_stop" %}" style="display: inherit; text-align: center; border-radius: 15px; text-decoration: none; color: inherit; padding: 4px; background-color: lightgreen;">➕</a>
  </div>
{% endblock %}

djangodjitney/routes/templates/routes/update_line.html
{% extends 'base.html' %} {% load static %} {% block content %}
<h2>Update Line</h2>
<form method="post">
  {% csrf_token %}
  {{ form }}
  <input type="submit" value="Update" />
</form>
{% endblock %}

djangodjitney/routes/templates/routes/update_station.html
{% extends 'base.html' %} {% load static %} {% block content %}
<h2>Update Station</h2>
<form method="post">
  {% csrf_token %}
  {{ form }}
  <input type="submit" value="Update" />
</form>
{% endblock %}

djangodjitney/routes/templates/routes/update_stop.html
{% extends 'base.html' %} {% load static %} {% block content %}
<h2>Update Stop</h2>
<form method="post">
  {% csrf_token %}
  {{ form }}
  <input type="submit" value="Update" />
</form>
{% endblock %}